export const MOCK_ISSUES = [
  {
    id: 1,
    column: "Monthly_Revenue",
    type: "Missing Values",
    dimension: "completeness",
    severity: "critical",
    count: 847,
    pct: "18.2%",
    fixed: false,
    diagnosis: "Zero revenue on weekends likely indicates the system records no transactions on non-working days rather than actual zero sales. These are missing values disguised as zeros. Recommend replacing weekend zeros with null, then forward-filling from the previous Friday's value for time-series continuity.",
    fix: "Replace weekend zeros with null + forward-fill",
  },
  {
    id: 2,
    column: "Customer_Name",
    type: "Near Duplicates",
    dimension: "uniqueness",
    severity: "critical",
    count: 134,
    pct: "2.9%",
    fixed: false,
    diagnosis: "Fuzzy matching identified 134 near-duplicate customer names differing by spacing, casing, or minor typos (e.g. 'Infosys Ltd' vs 'INFOSYS LTD' vs 'Infosys limited'). This inflates the unique customer count by ~12% and will skew customer-level aggregations.",
    fix: "Standardize to title-case + deduplicate by fuzzy threshold 0.9",
  },
  {
    id: 3,
    column: "Order_Date",
    type: "Format Inconsistency",
    dimension: "consistency",
    severity: "warning",
    count: 312,
    pct: "6.7%",
    fixed: false,
    diagnosis: "Three date formats co-exist: ISO-8601 (2024-03-01), DD/MM/YYYY (01/03/2024), and natural language (March 1, 2024). This likely results from data merged from multiple regional systems. Any date-based sorting or range filtering will produce incorrect results until unified.",
    fix: "Parse all formats → ISO-8601 YYYY-MM-DD standard",
  },
  {
    id: 4,
    column: "Discount_Pct",
    type: "Out-of-Range Values",
    dimension: "validity",
    severity: "warning",
    count: 23,
    pct: "0.5%",
    fixed: false,
    diagnosis: "23 rows have Discount_Pct > 100, with values up to 450%. These are almost certainly data entry errors — a discount percentage cannot exceed 100%. The pattern shows these all originate from the 'bulk_import_march' batch, suggesting a unit mismatch (raw discount amount entered instead of percentage).",
    fix: "Divide outlier values by 100 where value > 100 and < 1000",
  },
  {
    id: 5,
    column: "Product_SKU",
    type: "Missing Values",
    dimension: "completeness",
    severity: "warning",
    count: 201,
    pct: "4.3%",
    fixed: true,
    diagnosis: "Missing SKUs are clustered in rows where Category = 'Services'. Service-type line items don't use SKUs in this company's catalog system. These nulls are expected and structurally valid — not a data quality problem.",
    fix: "Fill with placeholder 'SVC-NA' for service rows",
  },
  {
    id: 6,
    column: "Employee_ID",
    type: "Exact Duplicates",
    dimension: "uniqueness",
    severity: "minor",
    count: 12,
    pct: "0.3%",
    fixed: false,
    diagnosis: "12 exact duplicate rows share the same Employee_ID and transaction date. The pattern matches known ETL pipeline re-run timestamps from March 14th. These are safe to drop — they are not genuine duplicate transactions.",
    fix: "Drop duplicate rows (keep first occurrence per ID+date)",
  },
  {
    id: 7,
    column: "Transaction_Amt",
    type: "Statistical Outliers",
    dimension: "accuracy",
    severity: "minor",
    count: 47,
    pct: "1.0%",
    fixed: false,
    diagnosis: "47 transaction amounts exceed 3 standard deviations from the mean. However, reviewing them shows they are legitimate high-value enterprise contracts (₹50L+). These should be kept but flagged with a boolean column 'is_high_value' to prevent them skewing standard analytics.",
    fix: "Add flag column 'is_high_value = True' for values > ₹50L",
  },
];

export const MOCK_COLUMNS = [
  { name: "Monthly_Revenue",  type: "float64",  nullPct: 18, uniquePct: 94, outlierPct: 3,  values: [42000, 38500, 0, 51200, 0, 44800, 0, 0, 55100, 47300] },
  { name: "Customer_Name",    type: "object",   nullPct: 0,  uniquePct: 61, outlierPct: 0,  values: ["Infosys Ltd", "TCS", "INFOSYS LTD", "Wipro", "TCS Limited", "HCL", "Wipro Ltd", "Infosys limited", "Tech Mahindra", "HCL Technologies"] },
  { name: "Order_Date",       type: "object",   nullPct: 0,  uniquePct: 88, outlierPct: 0,  values: ["2024-03-01", "01/03/2024", "March 1, 2024", "2024-03-02", "02/03/2024", "2024-03-03", "March 3, 2024", "2024-03-04", "04/03/2024", "2024-03-05"] },
  { name: "Discount_Pct",     type: "float64",  nullPct: 0,  uniquePct: 45, outlierPct: 1,  values: [12.5, 8.0, 450, 15.0, 300, 10.0, 5.0, 180, 20.0, 7.5] },
  { name: "Product_SKU",      type: "object",   nullPct: 4,  uniquePct: 72, outlierPct: 0,  values: ["SKU-001", "SKU-042", null, "SKU-007", null, "SVC-NA", "SKU-019", null, "SKU-003", "SKU-088"] },
  { name: "Employee_ID",      type: "int64",    nullPct: 0,  uniquePct: 99, outlierPct: 0,  values: [1001, 1002, 1003, 1001, 1004, 1005, 1002, 1006, 1007, 1003] },
  { name: "Transaction_Amt",  type: "float64",  nullPct: 0,  uniquePct: 97, outlierPct: 2,  values: [125000, 87500, 5200000, 340000, 4800000, 98000, 156000, 72000, 210000, 6100000] },
  { name: "Region",           type: "object",   nullPct: 1,  uniquePct: 12, outlierPct: 0,  values: ["West", "South", "North", "west", "SOUTH", "East", "North", "West", null, "south"] },
];

export const DQ_SCORES = {
  overall: 63,
  completeness: 78,
  uniqueness: 71,
  consistency: 55,
  validity: 60,
  accuracy: 88,
};
